spring.application.name=MaintenanceUser2

# データベース接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/net_service_db
spring.datasource.username=net_user
spring.datasource.password=net
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true

logging.level.com.example.taskmate.repository=DEBUG
